function [rxNet, trainInfo] = trainNeuralReceiver( ...
    trainData, valData, Lwin, decoderParams)
% TRAINNEURALRECEIVER
%
% Constroi e treina o receptor neural utilizando os conjuntos
% de treinamento e validacao fornecidos.

layersRx = buildNeuralReceiver( ...
    Lwin, ...
    decoderParams);

options = trainingOptions( ...
    decoderParams.solverName, ...
    "MaxEpochs", decoderParams.numEpochs, ...
    "MiniBatchSize", decoderParams.miniBatchSize, ...
    "InitialLearnRate", decoderParams.initialLearnRate, ...
    "Shuffle", decoderParams.shuffle, ...
    "ValidationData", {valData.X, valData.Y}, ...
    "ValidationFrequency", ...
    decoderParams.validationFrequency, ...
    "Plots", decoderParams.trainingPlot, ...
    "Verbose", decoderParams.verbose);

[rxNet, trainInfo] = trainNetwork( ...
    trainData.X, ...
    trainData.Y, ...
    layersRx, ...
    options);

end
